#!/usr/bin/env bash
# Build the Coach Checkin Watch App .prg for the Forerunner 255 on Linux.
#
# Same SDK story as build.sh (public tools; one-time login only for the fr255
# device profile). EXTRA step: the Bearer token for the coach ingest endpoint is
# injected at compile time into watchapp/source-secret/Secret.mc (gitignored), so
# the secret is compiled into the .prg but never enters the public repo.
#
# Token source (first hit wins):
#   1) $COACH_INGEST_TOKEN
#   2) ~/减肥机制/config/secrets.toml  -> [ingest].token
#   (none → builds anyway with an empty token; the app just skips upload)
#
# Endpoint:  $COACH_INGEST_URL  (default https://api.jungerpf.top/coach/ingest)
#
# Usage:  ./build-app.sh   ->  build/CoachCheckin.prg
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$REPO_DIR/watchapp"
OUT_DIR="$REPO_DIR/build"
DEVICE="${GARMIN_DEVICE:-fr255}"
KEY="${GARMIN_KEY:-$HOME/.garmin_dev/developer_key.der}"
SECRETS_TOML="${COACH_SECRETS_TOML:-$HOME/减肥机制/config/secrets.toml}"
URL="${COACH_INGEST_URL:-https://api.jungerpf.top/coach/ingest}"
export PATH="$HOME/.local/bin:$PATH"

CIQ_ROOT="$HOME/.Garmin/ConnectIQ"
SDKS_ROOT="$CIQ_ROOT/Sdks"
DEVICES_DIR="$CIQ_ROOT/Devices"
mkdir -p "$OUT_DIR" "$SDKS_ROOT" "$APP_DIR/source-secret"

# 0) Inject the token into the gitignored Secret.mc (never committed).
TOKEN="${COACH_INGEST_TOKEN:-}"
if [ -z "$TOKEN" ] && [ -f "$SECRETS_TOML" ]; then
  TOKEN="$(python3 - "$SECRETS_TOML" <<'PY'
import sys
try:
    import tomllib
    with open(sys.argv[1], "rb") as f:
        print(tomllib.load(f).get("ingest", {}).get("token", ""))
except Exception:
    print("")
PY
)"
fi
if [ -z "$TOKEN" ]; then
  echo "⚠ no ingest token found (env COACH_INGEST_TOKEN or $SECRETS_TOML [ingest].token)."
  echo "  Building with an EMPTY token — the app will queue events but skip upload."
fi
# write Secret.mc with safely-escaped literals via python (no token echo to stdout)
python3 - "$APP_DIR/source-secret/Secret.mc" "$URL" "$TOKEN" <<'PY'
import json, sys
path, url, token = sys.argv[1], sys.argv[2], sys.argv[3]
open(path, "w").write(
    "// AUTO-GENERATED by build-app.sh — DO NOT COMMIT (gitignored).\n"
    "(:background)\n"
    "module Secret {\n"
    f"    const COACH_URL = {json.dumps(url)};\n"
    f"    const COACH_TOKEN = {json.dumps(token)};\n"
    "}\n"
)
PY
echo "· token injected: $([ -n "$TOKEN" ] && echo yes || echo 'EMPTY') → endpoint $URL"

# 1) SDK tools — PUBLIC, no Garmin account. Reuse cache or download latest.
MONKEYC="$(ls -d "$SDKS_ROOT"/connectiq-sdk-lin-*/bin/monkeyc 2>/dev/null | sort | tail -1 || true)"
if [ -z "$MONKEYC" ] || [ ! -x "$MONKEYC" ]; then
  echo "· no local SDK — downloading the public Connect IQ SDK (no account needed)…"
  ZIP="$(curl -sS https://developer.garmin.com/downloads/connect-iq/sdks/sdks.json \
        | python3 -c "import sys,json;print(json.load(sys.stdin)[-1]['linux'])")"
  curl -sSL -o "/tmp/$ZIP" "https://developer.garmin.com/downloads/connect-iq/sdks/$ZIP"
  DEST="$SDKS_ROOT/${ZIP%.zip}"
  mkdir -p "$DEST"; unzip -q -o "/tmp/$ZIP" -d "$DEST"; chmod +x "$DEST"/bin/* 2>/dev/null || true
  MONKEYC="$DEST/bin/monkeyc"
fi
echo "· compiler: $("$MONKEYC" --version)"

# 2) Device profile — the ONE gated piece (needs a one-time Garmin login).
if [ ! -d "$DEVICES_DIR/$DEVICE" ]; then
  command -v connect-iq-sdk-manager >/dev/null 2>&1 || {
    echo "✗ connect-iq-sdk-manager (lindell CLI) is required to fetch the $DEVICE profile."; exit 1; }
  echo "· fetching '$DEVICE' device profile via Garmin (one-time login required)…"
  connect-iq-sdk-manager device download -d "$DEVICE" || {
    echo "✗ Could not download the $DEVICE profile — run  ! connect-iq-sdk-manager login  then retry."
    exit 1; }
fi

# 3) Compile.
[ -f "$KEY" ] || { echo "✗ signing key not found at $KEY (see docs/sideload-guide.md)"; exit 1; }
echo "· compiling Coach Checkin for $DEVICE…"
"$MONKEYC" -d "$DEVICE" -f "$APP_DIR/monkey.jungle" -o "$OUT_DIR/CoachCheckin.prg" -y "$KEY" -w

echo "✓ built $OUT_DIR/CoachCheckin.prg"
echo "  Sideload: plug in the FR255 over USB, copy CoachCheckin.prg into GARMIN/Apps/,"
echo "  eject, then on the watch it appears under the app list / Activities & Apps."
