#!/usr/bin/env bash
# Build the 4 single-action "tile" apps (忍住 / 撑一下 / 抽了 / 喝水) for the FR255.
# Each is its own CIQ watch-app (own app id) with one glance card, sharing one source
# tree. Per build, the action + Chinese label are injected into gitignored generated
# files (source-gen/, res-gen/); same token-injection story as build-app.sh.
#
# Glance design: the card shows the app's LAUNCHER ICON (a designed 40x40 PNG, system-
# drawn) + a text label drawn by the GlanceView (text only: setColor/clear/drawText +
# system FONT_GLANCE). CRITICAL (FR255-specific, CIQ_LOG-confirmed): a non-music device
# renders glances through an off-screen "Background UI Update" lifecycle that runs the app
# in the restricted (:glance) VM, calling AppBase.onStart() → getGlanceView() → onUpdate().
# onStart() therefore must NOT invoke any foreground-only symbol (e.g. coachNet()) — doing
# so throws "Illegal Access: Failed invoking <symbol>" and the firmware silently falls back
# to the bare launcher icon (no text). So TileApp.onStart is empty and foreground setup
# lives in getInitialView (never run in glance). The glance is NOT gated on a Background
# service (that earlier theory was wrong, per Glances.html) → tiles are pure foreground apps.
#
# Usage:  GARMIN_DEVICE=fr255 ./build-tiles.sh
# Output: build/sideload/Tile-{resist,hold,smoked,water}-fr255.prg
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
T_DIR="$REPO_DIR/watchapp-tiles"
OUT_DIR="$REPO_DIR/build/sideload"
DEVICE="${GARMIN_DEVICE:-fr255}"
KEY="${GARMIN_KEY:-$HOME/.garmin_dev/developer_key.der}"
SECRETS_TOML="${COACH_SECRETS_TOML:-$HOME/减肥机制/config/secrets.toml}"
URL="${COACH_INGEST_URL:-https://api.jungerpf.top/coach/ingest}"
export PATH="$HOME/.local/bin:$PATH"

SDKS_ROOT="$HOME/.Garmin/ConnectIQ/Sdks"
mkdir -p "$OUT_DIR" "$T_DIR/source-gen" "$T_DIR/res-gen/strings" "$T_DIR/res-gen/drawables"

# token (env wins, else secrets.toml [ingest].token)
TOKEN="${COACH_INGEST_TOKEN:-}"
if [ -z "$TOKEN" ] && [ -f "$SECRETS_TOML" ]; then
  TOKEN="$(python3 - "$SECRETS_TOML" <<'PY'
import sys
try:
    import tomllib
    with open(sys.argv[1], "rb") as f:
        print(tomllib.load(f).get("ingest", {}).get("token", ""))
except Exception:
    print("")
PY
)"
fi
[ -n "$TOKEN" ] || echo "⚠ no ingest token (env COACH_INGEST_TOKEN or $SECRETS_TOML) — tiles will queue but skip upload."

# shared, gitignored Secret.mc (no token echo to stdout)
python3 - "$T_DIR/source-gen/Secret.mc" "$URL" "$TOKEN" <<'PY'
import json, sys
path, url, token = sys.argv[1], sys.argv[2], sys.argv[3]
open(path, "w").write(
    "// AUTO-GENERATED by build-tiles.sh — DO NOT COMMIT (gitignored).\n"
    "module Secret {\n"
    f"    const COACH_URL = {json.dumps(url)};\n"
    f"    const COACH_TOKEN = {json.dumps(token)};\n"
    "}\n")
PY
echo "· token injected: $([ -n "$TOKEN" ] && echo yes || echo EMPTY) → $URL"

MONKEYC="$(ls -d "$SDKS_ROOT"/connectiq-sdk-lin-*/bin/monkeyc 2>/dev/null | sort | tail -1 || true)"
[ -n "$MONKEYC" ] && [ -x "$MONKEYC" ] || { echo "✗ no Connect IQ SDK monkeyc found under $SDKS_ROOT"; exit 1; }
[ -f "$KEY" ] || { echo "✗ signing key not found at $KEY"; exit 1; }
echo "· compiler: $("$MONKEYC" --version)"

# drawables.xml (static, points at the per-tile launcher_icon.png in res-gen)
printf '%s\n' '<drawables>' '    <bitmap id="LauncherIcon" filename="launcher_icon.png"/>' '</drawables>' \
  > "$T_DIR/res-gen/drawables/drawables.xml"

# key|ACTION|LABEL
tiles=( "resist|忍住" "hold|撑一下" "smoked|抽了" "water|喝水" )

for spec in "${tiles[@]}"; do
  IFS='|' read -r t label <<< "$spec"
  # foreground action + a self-contained text-only glance (literal label) + strings
  python3 - "$T_DIR/source-gen/TileFg.mc" "$T_DIR/source-gen/TileGlance.mc" "$T_DIR/res-gen/strings/strings.xml" "$t" "$label" <<'PY'
import json, sys
import xml.sax.saxutils as x
fg, glc, strings, action, label = sys.argv[1:6]
def s(v): return json.dumps(v, ensure_ascii=False)  # keep raw UTF-8 literals
open(fg, "w", encoding="utf-8").write(
    "// AUTO-GENERATED by build-tiles.sh.\n"
    "module Tile {\n"
    f"    const ACTION = {s(action)};\n"
    "}\n")
# Text-only glance (proven-safe: only setColor/clear/drawText). Icon = launcher PNG.
open(glc, "w", encoding="utf-8").write(
    "// AUTO-GENERATED by build-tiles.sh.\n"
    "import Toybox.WatchUi;\n"
    "import Toybox.Graphics;\n"
    "import Toybox.Lang;\n"
    "(:glance)\n"
    "class TileGlanceView extends WatchUi.GlanceView {\n"
    "    function initialize() { GlanceView.initialize(); }\n"
    "    function onUpdate(dc as Graphics.Dc) as Void {\n"
    "        dc.setColor(Graphics.COLOR_TRANSPARENT, Graphics.COLOR_BLACK);\n"
    "        dc.clear();\n"
    "        dc.setColor(Graphics.COLOR_WHITE, Graphics.COLOR_TRANSPARENT);\n"
    "        var pad = 50;  // clear the fixed 40px FR255 glance launcher icon + ~10px gap\n"
    "                       // (x=4 overlapped the icon; dc.getHeight()+12 sat too far right)\n"
    f"        dc.drawText(pad, dc.getHeight() / 2, Graphics.FONT_MEDIUM, {s(label)},\n"
    "                    Graphics.TEXT_JUSTIFY_LEFT | Graphics.TEXT_JUSTIFY_VCENTER);\n"
    "    }\n"
    "}\n")
open(strings, "w", encoding="utf-8").write(
    '<strings>\n    <string id="AppName">' + x.escape(label) + '</string>\n</strings>\n')
PY
  # per-tile designed launcher icon (system draws this in the glance row + app list)
  cp "$T_DIR/icons/$t.png" "$T_DIR/res-gen/drawables/launcher_icon.png"
  echo "· compiling '$t' ($label)…"
  "$MONKEYC" -d "$DEVICE" -f "$T_DIR/$t.jungle" -o "$OUT_DIR/Tile-$t-fr255.prg" -y "$KEY" -w
  echo "  ✓ $OUT_DIR/Tile-$t-fr255.prg"
done

echo "── md5 ──"
md5sum "$OUT_DIR"/Tile-*-fr255.prg
