#!/usr/bin/env bash
# Build the Coach Face .prg for the Forerunner 255 on Linux, end to end.
#
# What needs a Garmin account, and what does NOT (verified 2026-06):
#   - The SDK TOOLS (monkeyc/connectiq/monkeydo) download from a PUBLIC URL with
#     NO account.  This script fetches+caches them automatically.
#   - The per-device PROFILE (Devices/fr255) is gated: api.gcs.garmin.com returns
#     401 without a token. So you must log in ONCE to pull the fr255 profile:
#         ! connect-iq-sdk-manager login        # global Garmin account (.com)
#     (run it yourself in a real terminal so your password never reaches the AI;
#      a China-region 国行 account may not work here — register a free global one
#      at developer.garmin.com if login fails.)
#   - Installing the built .prg on the watch (USB sideload) needs NO account.
#
# After the one-time login:  ./build.sh   ->  build/CoachFace.prg
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WF_DIR="$REPO_DIR/watchface"
OUT_DIR="$REPO_DIR/build"
DEVICE="${GARMIN_DEVICE:-fr255}"
KEY="${GARMIN_KEY:-$HOME/.garmin_dev/developer_key.der}"
export PATH="$HOME/.local/bin:$PATH"

CIQ_ROOT="$HOME/.Garmin/ConnectIQ"
SDKS_ROOT="$CIQ_ROOT/Sdks"
DEVICES_DIR="$CIQ_ROOT/Devices"
mkdir -p "$OUT_DIR" "$SDKS_ROOT" "$WF_DIR/source-secret"

# 0) Inject the coach summary URL (with the READ-ONLY summary token) into a
#    gitignored Secret.mc, so a USB-sideloaded face (which has NO phone settings
#    UI to set CoachApiUrl) can reach the backend out of the box. The face still
#    prefers a user-set CoachApiUrl property if present; this is the fallback.
#    URL source (first hit wins):
#      1) $COACH_FACE_URL
#      2) derived from the coach backend config ($COACH_PROJECT_DIR, default ~/减肥机制)
#      3) empty → the face runs as a pure native face (no background calls)
COACH_PROJECT_DIR="${COACH_PROJECT_DIR:-$HOME/减肥机制}"
FACE_URL="${COACH_FACE_URL:-}"
if [ -z "$FACE_URL" ] && [ -x "$COACH_PROJECT_DIR/.venv/bin/python" ]; then
  FACE_URL="$("$COACH_PROJECT_DIR/.venv/bin/python" - "$COACH_PROJECT_DIR" <<'PY' 2>/dev/null || true
import sys, urllib.parse as u
sys.path.insert(0, sys.argv[1])
try:
    from coach.config import load_settings
    print("https://api.jungerpf.top/coach/summary?k=" + u.quote(load_settings().ingest_summary_token))
except Exception:
    print("")
PY
)"
fi
# write Secret.mc with a safely-escaped literal via python (no token echo to stdout)
python3 - "$WF_DIR/source-secret/Secret.mc" "$FACE_URL" <<'PY'
import json, sys
path, url = sys.argv[1], sys.argv[2]
open(path, "w").write(
    "// AUTO-GENERATED by build.sh — DO NOT COMMIT (gitignored).\n"
    "(:background)\n"
    "module Secret {\n"
    f"    const FACE_URL = {json.dumps(url)};\n"
    "}\n"
)
PY
echo "· face coach URL injected: $([ -n "$FACE_URL" ] && echo yes || echo 'EMPTY (native-only face)')"

# 1) SDK tools — PUBLIC, no Garmin account. Use a cached one or download latest.
MONKEYC="$(ls -d "$SDKS_ROOT"/connectiq-sdk-lin-*/bin/monkeyc 2>/dev/null | sort | tail -1 || true)"
if [ -z "$MONKEYC" ] || [ ! -x "$MONKEYC" ]; then
  echo "· no local SDK — downloading the public Connect IQ SDK (no account needed)…"
  ZIP="$(curl -sS https://developer.garmin.com/downloads/connect-iq/sdks/sdks.json \
        | python3 -c "import sys,json;print(json.load(sys.stdin)[-1]['linux'])")"
  curl -sSL -o "/tmp/$ZIP" "https://developer.garmin.com/downloads/connect-iq/sdks/$ZIP"
  DEST="$SDKS_ROOT/${ZIP%.zip}"
  mkdir -p "$DEST"; unzip -q -o "/tmp/$ZIP" -d "$DEST"; chmod +x "$DEST"/bin/* 2>/dev/null || true
  MONKEYC="$DEST/bin/monkeyc"
fi
echo "· compiler: $("$MONKEYC" --version)"

# 2) Device profile — the ONE gated piece (needs the one-time login above).
if [ ! -d "$DEVICES_DIR/$DEVICE" ]; then
  command -v connect-iq-sdk-manager >/dev/null 2>&1 || {
    echo "✗ connect-iq-sdk-manager (lindell CLI) is required to fetch the $DEVICE profile."; exit 1; }
  echo "· fetching '$DEVICE' device profile via Garmin (one-time login required)…"
  connect-iq-sdk-manager device download -d "$DEVICE" || {
    echo ""
    echo "✗ Could not download the $DEVICE profile — you are probably not logged in."
    echo "  In a REAL terminal run:   ! connect-iq-sdk-manager login"
    echo "  (global Garmin account; register free at developer.garmin.com if 国行 fails)"
    echo "  then re-run:              ./build.sh"
    exit 1; }
fi

# 3) Compile.
[ -f "$KEY" ] || { echo "✗ signing key not found at $KEY (see docs/sideload-guide.md)"; exit 1; }
echo "· compiling for $DEVICE…"
"$MONKEYC" -d "$DEVICE" -f "$WF_DIR/monkey.jungle" -o "$OUT_DIR/CoachFace.prg" -y "$KEY" -w

echo "✓ built $OUT_DIR/CoachFace.prg"
echo "  Sideload: plug in the FR255 over USB, copy CoachFace.prg into GARMIN/Apps/,"
echo "  eject, then on the watch hold UP > Watch Face > Coach Face > Apply."
